-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 23:59:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Sintomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sintomas` (
  `id_sintomas` INT NOT NULL,
  `Febre` VARCHAR(45) NOT NULL,
  `DificuldadeRespiratoria` VARCHAR(45) NOT NULL,
  `Tosse` VARCHAR(45) NOT NULL,
  `Coriza` VARCHAR(45) NOT NULL,
  `DorGarganta` VARCHAR(45) NOT NULL,
  `Diarreia` VARCHAR(45) NOT NULL,
  `Cefaleia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sintomas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tempo` (
  `id_tempo` INT NOT NULL AUTO_INCREMENT,
  `DataNotificacao` VARCHAR(45) NULL,
  `DataCadastro` VARCHAR(45) NULL,
  `DataDiagnostico` VARCHAR(45) NULL,
  `DataColeta_RT_PCR` VARCHAR(45) NULL,
  `DataColetaTesteRapido` VARCHAR(45) NULL,
  `DataColetaSorologia` VARCHAR(45) NULL,
  `DataColetaSorologiaIGG` VARCHAR(45) NULL,
  `DataEncerramento` VARCHAR(45) NULL,
  `DataObito` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tempo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comorbidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comorbidade` (
  `id_comorbidade` INT NOT NULL AUTO_INCREMENT,
  `ComorbidadePulmao` VARCHAR(45) NOT NULL,
  `ComorbidadeCardio` VARCHAR(45) NOT NULL,
  `ComorbidadeRenal` VARCHAR(45) NOT NULL,
  `ComorbidadeDiabetes` VARCHAR(45) NOT NULL,
  `ComorbidadeTabagismo` VARCHAR(45) NOT NULL,
  `ComorbidadeObesidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comorbidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Moradia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Moradia` (
  `id_moradia` INT NOT NULL,
  `Municipio` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NULL,
  PRIMARY KEY (`id_moradia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Caracteristicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Caracteristicas` (
  `id_caracteristicas` INT NOT NULL,
  `Gestante` VARCHAR(45) NOT NULL,
  `ProfissionalSaude` VARCHAR(45) NOT NULL,
  `PossuiDeficiencia` VARCHAR(45) NOT NULL,
  `MoradorDeRua` VARCHAR(45) NOT NULL,
  `ViagemBrasil` VARCHAR(45) NOT NULL,
  `ViagemInternacional` VARCHAR(45) NOT NULL,
  `FicouInternado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_caracteristicas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Situacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Situacao` (
  `id_situacao` INT NOT NULL,
  `Classificacao` VARCHAR(45) NOT NULL,
  `Evolucao` VARCHAR(45) NOT NULL,
  `CriterioConfirmacao` VARCHAR(45) NOT NULL,
  `StatusNotificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_situacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Testes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Testes` (
  `id_testes` INT NOT NULL,
  `ResultadoRT_PCR` VARCHAR(45) NOT NULL,
  `ResultadoTesteRapido` VARCHAR(45) NOT NULL,
  `ResultadoSorologia` VARCHAR(45) NOT NULL,
  `ResultadoSorologia_IGG` VARCHAR(45) NOT NULL,
  `TipoTesteRapido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_testes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Informacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Informacoes` (
  `id_informacoes` INT NOT NULL,
  `FaixaEtaria` VARCHAR(45) NOT NULL,
  `IdadeNaDataNotificacao` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `RacaCor` VARCHAR(45) NOT NULL,
  `Escolaridade` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_informacoes`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`fato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fato` (
  `mortes` INT NOT NULL,
  `Informacoes_id` INT NOT NULL,
  `Moradia_id` INT NOT NULL,
  `Tempo_id` INT NOT NULL,
  `Caracteristica_id` INT NOT NULL,
  `Comorbidade_id` INT NOT NULL,
  `Sintomas_id` INT NOT NULL,
  `Situacao_id` INT NOT NULL,
  `Testes_id` INT NOT NULL,
  `Informacoes_id_informacoes` INT,
  `Moradia_id_moradia` INT,
  `Tempo_id_tempo` INT,
  `Caracteristicas_id_caracteristicas` INT,
  `Comorbidade_id_comorbidade` INT,
  `Sintomas_id_sintomas` INT,
  `Situacao_id_situacao` INT,
  `Testes_id_testes` INT,
  PRIMARY KEY (`mortes`),
  INDEX `fk_fato_Tempo_idx` (`Tempo_id_tempo` ASC) VISIBLE,
  INDEX `fk_fato_Comorbidade1_idx` (`Comorbidade_id_comorbidade` ASC) VISIBLE,
  INDEX `fk_fato_Sintomas1_idx` (`Sintomas_id_sintomas` ASC) VISIBLE,
  INDEX `fk_fato_Moradia1_idx` (`Moradia_id_moradia` ASC) VISIBLE,
  INDEX `fk_fato_Caracteristicas1_idx` (`Caracteristicas_id_caracteristicas` ASC) VISIBLE,
  INDEX `fk_fato_Situacao1_idx` (`Situacao_id_situacao` ASC) VISIBLE,
  INDEX `fk_fato_Testes1_idx` (`Testes_id_testes` ASC) VISIBLE,
  INDEX `fk_fato_Informacoes1_idx` (`Informacoes_id_informacoes` ASC) VISIBLE,
  CONSTRAINT `fk_fato_Tempo`
    FOREIGN KEY (`Tempo_id_tempo`)
    REFERENCES `mydb`.`Tempo` (`id_tempo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Comorbidade1`
    FOREIGN KEY (`Comorbidade_id_comorbidade`)
    REFERENCES `mydb`.`Comorbidade` (`id_comorbidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Sintomas1`
    FOREIGN KEY (`Sintomas_id_sintomas`)
    REFERENCES `mydb`.`Sintomas` (`id_sintomas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Moradia1`
    FOREIGN KEY (`Moradia_id_moradia`)
    REFERENCES `mydb`.`Moradia` (`id_moradia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Caracteristicas1`
    FOREIGN KEY (`Caracteristicas_id_caracteristicas`)
    REFERENCES `mydb`.`Caracteristicas` (`id_caracteristicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Situacao1`
    FOREIGN KEY (`Situacao_id_situacao`)
    REFERENCES `mydb`.`Situacao` (`id_situacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Testes1`
    FOREIGN KEY (`Testes_id_testes`)
    REFERENCES `mydb`.`Testes` (`id_testes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_Informacoes1`
    FOREIGN KEY (`Informacoes_id_informacoes`)
    REFERENCES `mydb`.`Informacoes` (`id_informacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

select * from mydb.moradia limit 10;
  
insert into `Sintomas`
select `id`,
`Febre`,
`DificuldadeRespiratoria`,
`Tosse`,
`Coriza`,
`DorGarganta`,
`Diarreia`,
`Cefaleia`
  from covid19_es.db_covid;

insert into `Tempo`
select `id`,
`DataNotificacao`,
`DataCadastro`,
`DataDiagnostico`,
`DataColeta_RT_PCR`,
`DataColetaTesteRapido`,
`DataColetaSorologia`,
`DataColetaSorologiaIGG`,
`DataEncerramento`,
`DataObito`
  from covid19_es.db_covid;
  
insert into `Comorbidade`
select `id`,
`ComorbidadePulmao`,
`ComorbidadeCardio`,
`ComorbidadeRenal`,
`ComorbidadeDiabetes`,
`ComorbidadeTabagismo`,
`ComorbidadeObesidade`
  from covid19_es.db_covid;
  
insert into `Moradia`
select `id`,
  `Municipio`,
  `Bairro`
  from covid19_es.db_covid;

insert into `Caracteristicas`
select `id`,
`Gestante`,
`ProfissionalSaude`,
`PossuiDeficiencia`,
`MoradorDeRua`,
`ViagemBrasil`,
`ViagemInternacional`,
`FicouInternado`
  from covid19_es.db_covid;

insert into `Situacao`
select `id`,
`Classificacao`,
`Evolucao`,
`CriterioConfirmacao`,
`StatusNotificacao`
  from covid19_es.db_covid;

insert into `Testes`
select `id`,
`ResultadoRT_PCR`,
`ResultadoTesteRapido`,
`ResultadoSorologia`,
`ResultadoSorologia_IGG`,
`TipoTesteRapido`
  from covid19_es.db_covid;

insert into `Informacoes`
select `id`,
`FaixaEtaria`,
`IdadeNaDataNotificacao`,
`Sexo`,
`RacaCor`,
`Escolaridade`
  from covid19_es.db_covid;

insert into `mydb`.`fato` (mortes, Informacoes_id, Moradia_id, Tempo_id, Caracteristica_id, Comorbidade_id, Sintomas_id, Situacao_id, Testes_id)
select `id`,
`id`,
`id`,
`id`,
`id`,
`id`,
`id`,
`id`,
`id`
from covid19_es.db_covid;